### ISSUE TITLE
К заданию №4.

### ISSUE THREAD

**Issue by FlashAnton** [ArsenEuroDed/Prog-Works#4]
Здесь запланировано обсуждение выполнения задания №4.

**Comment by FlashAnton** [comment]
Здравствуйте!

Вычислительный процесс разомкнут:
![image](https://github.com/ArsenEuroDed/Prog-Works/assets/95698986/d4e89b93-901c-4b88-89c9-b822aa9fe073)
![image](https://github.com/ArsenEuroDed/Prog-Works/assets/95698986/9109c26c-6d80-4782-b8ff-75d40f8b7c39)

Код избыточен:
![image](https://github.com/ArsenEuroDed/Prog-Works/assets/95698986/8f4d3c8e-6e1a-4653-80ec-6e75ef44b1c4)

Форматирование, явно, "поехало". Приведите его в порядок:
![image](https://github.com/ArsenEuroDed/Prog-Works/assets/95698986/78c240cb-70fc-4544-ba52-79137e31d93b)
![image](https://github.com/ArsenEuroDed/Prog-Works/assets/95698986/de03f293-163d-447d-b172-1fa30bc95f78)

**Comment by ArsenEuroDed** [comment]
Здравствуйте, введен и загружен отчёт с исправлениями

**Comment by FlashAnton** [comment]
Здравствуйте!

С правками согласен.

**Зачтено**
